// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIDVABGY-xdHT75E8rbg2Tan879LG-R-s',
    appId: '1:733440569004:web:8a205e998b353f5ab0b909',
    messagingSenderId: '733440569004',
    projectId: 'ev-charging-3a187',
    authDomain: 'ev-charging-3a187.firebaseapp.com',
    storageBucket: 'ev-charging-3a187.appspot.com',
    measurementId: 'G-PQRFH9T85R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCusLT1B5q2AHsvTY0En85hIwd-RRIgOf0',
    appId: '1:733440569004:android:1b3a00a78f02d3a4b0b909',
    messagingSenderId: '733440569004',
    projectId: 'ev-charging-3a187',
    storageBucket: 'ev-charging-3a187.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzAMwGT_pvmKR2w4R-aXbq6hhTb0aY80I',
    appId: '1:733440569004:ios:db3e5651874f40b0b0b909',
    messagingSenderId: '733440569004',
    projectId: 'ev-charging-3a187',
    storageBucket: 'ev-charging-3a187.appspot.com',
    iosBundleId: 'com.example.evCharging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzAMwGT_pvmKR2w4R-aXbq6hhTb0aY80I',
    appId: '1:733440569004:ios:db3e5651874f40b0b0b909',
    messagingSenderId: '733440569004',
    projectId: 'ev-charging-3a187',
    storageBucket: 'ev-charging-3a187.appspot.com',
    iosBundleId: 'com.example.evCharging',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIDVABGY-xdHT75E8rbg2Tan879LG-R-s',
    appId: '1:733440569004:web:d3f859f482c83a9db0b909',
    messagingSenderId: '733440569004',
    projectId: 'ev-charging-3a187',
    authDomain: 'ev-charging-3a187.firebaseapp.com',
    storageBucket: 'ev-charging-3a187.appspot.com',
    measurementId: 'G-YRPF3D2K6F',
  );
}
